- name: add docker repo
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: install docker
  yum: name=docker-engine state=installed

- name: start docker
  service: name=docker state=started

- name: enable docker
  service: name=docker enabled=yes

