- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh > ~/docker_installation creates=~/docker_installation

- name: enable docker
  service: name=docker enabled=yes

- name: start docker
  service: name=docker state=started

