- name: configure systemd for rocbot
  template: src=rocbot.service dest=/etc/systemd/system/rocbot.service
  notify:
    - reload systemd
    - restart rocbot

- name: enable rocbot
  service: name=rocbot enabled=yes

- name: start rocbot
  service: name=rocbot state=started

