- name: install ansible requirements
  hosts: all
  user: root
  gather_facts: no
  tasks:
    - name: install python
      raw: apt-get install -y python

- name: setup base components
  hosts: all
  user: root
  roles:
    - base
    - docker
    - vim
    - users

- name: configure vim
  hosts: all
  user: geowa4
  roles:
    - vim

- name: configure irssi
  hosts: irc
  user: geowa4
  roles:
    - irssi

- name: run rocbot
  hosts: hubot
  user: rocbot
  become: yes
  roles:
    - rocbot
    - vim

